services:

  web:
    build: ./app
    ports:
      - "${WEB_PORT}:80"
    environment:
      - AMBIENTE=${AMBIENTE}
    networks:
      - sirius-network

  api:
    image: nginx:alpine
    volumes:
      - ./api:/usr/share/nginx/html
    ports:
      - "${API_PORT}:80"
    environment:
      - AMBIENTE=${AMBIENTE}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - sirius-network

networks:
  sirius-network:
    driver: bridge
