version: '3.8'

services:

  web:
    build: ./app
    ports:
      - "8080:80"
    networks:
      - sirius-network

  api:
    image: nginx:alpine
    volumes:
      - ./api:/usr/share/nginx/html
    ports:
      - "8081:80"
    networks:
      - sirius-network

networks:
  sirius-network:
    driver: bridge
